# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc7f998db47fa0703afbb7a59be2b51cdde6c72841fc120c0e0d51f50f2f6db2f1305a7ae2397e2bfa95da88c369b20a452ad79d291ac72221a6f4f3f2f32d56

test:
  secret_key_base: a8db198d6f6df2e6553da72d43e1a4957fade4396e09a07ff6c7a473fcce7e46c3788d83b741dc90f6683e503f1c2bab27640b315680c1fa07055330932ef912

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
